nodes:
  # Nœud indexer (OpenSearch)
  indexer:
    - name: wazuh.indexer
      ip: wazuh.indexer

  # Nœud serveur (manager)
  server:
    - name: wazuh.manager
      ip: wazuh.manager

  # Nœud dashboard
  dashboard:
    - name: wazuh.dashboard
      ip: wazuh.dashboard
